# Serve from the repo root (no build step)
[build]
  publish = "./"

# Cache static libs a bit
[[headers]]
  for = "/vendor/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Import maps and modules should be same-origin and JSON
[[headers]]
  for = "/src/importmap.json"
  [headers.values]
    Content-Type = "application/importmap+json; charset=utf-8"

# Tight CSP that still allows external module file *and* your JSON import map
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self'; connect-src 'self'; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; font-src 'self' data:; object-src 'none'; base-uri 'self'; frame-ancestors 'self';"
    X-Content-Type-Options = "nosniff"
