[build]
  publish = "./"   # static site, no build

# Cache vendor libs for a long time
[[headers]]
  for = "/vendor/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Allow inline import map and a CDN fallback for Three.js (if local copies are missing)
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net;
      connect-src 'self' https://cdn.jsdelivr.net;
      img-src 'self' data: blob:;
      style-src 'self' 'unsafe-inline';
      font-src 'self' data:;
      object-src 'none';
      base-uri 'self';
      frame-ancestors 'self';
    """
    X-Content-Type-Options = "nosniff"
