[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
  # Strict but Import-Map friendly (no inline scripts required)
  Content-Security-Policy = '''
    default-src 'self';
    script-src 'self';
    connect-src 'self';
    img-src 'self' data:;
    style-src 'self' 'unsafe-inline';
    font-src 'self' data:;
    object-src 'none';
    base-uri 'self';
    frame-ancestors 'self';
    worker-src 'self' blob:;
  '''
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "no-referrer"
  Permissions-Policy = "camera=(), microphone=(), geolocation=()"
