[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
  # tighten as needed; keep NO inline JS
  Content-Security-Policy = """
    default-src 'self';
    script-src 'self' https://cdn.jsdelivr.net;
    connect-src 'self';
    img-src 'self' data: blob: https:;
    style-src 'self' 'unsafe-inline';
    font-src 'self' data: https://fonts.gstatic.com;
    worker-src 'self' blob:;
    object-src 'none';
    frame-ancestors 'self';
    base-uri 'self';
    upgrade-insecure-requests;
  """
  Referrer-Policy = "strict-origin-when-cross-origin"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "SAMEORIGIN"
  Permissions-Policy = "accelerometer=(), camera=(), microphone=(), geolocation=()"
