# netlify.toml
[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = '''
    default-src 'self';
    script-src 'self' https://cdn.jsdelivr.net;
    connect-src 'self' https://cdn.jsdelivr.net;
    img-src 'self' data: https:;
    style-src 'self' 'unsafe-inline';
    font-src 'self' data:;
    frame-ancestors 'self';
    base-uri 'self';
    object-src 'none';
  '''
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Permissions-Policy = "camera=(), microphone=(), geolocation=()"
