[build]
  publish = "."

# Strict but simple CSP – only local scripts. (We’re not using any CDN.)
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self';
      style-src 'self' 'unsafe-inline';
      img-src 'self' data:;
      font-src 'self' data:;
      connect-src 'self';
      object-src 'none';
      base-uri 'self';
      frame-ancestors 'self';
    """
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
