# Netlify config for a static site (no build step)
[build]
  publish = "."

# Light CSP that allows our two CDNs for ESM modules
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://unpkg.com https://cdn.jsdelivr.net; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; font-src 'self' data: https:; connect-src 'self' https://unpkg.com https://cdn.jsdelivr.net; object-src 'none'; frame-ancestors 'self'; base-uri 'self'; worker-src 'self' blob:"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
